import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
  site: 'https://www.saharastartours.com',
  trailingSlash: 'never',
  integrations: [sitemap()],
  redirects: {
    // Root pages redirects (.html to clean URLs)
    '/about.html': '/about',
    '/desert-tours.html': '/desert-tours',
    '/imperial-cities.html': '/imperial-cities',
    '/day-trips.html': '/day-trips',
    '/activities.html': '/activities',

    // Original tour .html files -> clean Astro tour routes
    '/tours/itinerary-6-days-tour-from-casablanca.html': '/tours/6-days-desert-tour-from-casablanca',
    '/tours/7-day-morocco-tour-from-casablanca.html': '/tours/7-day-morocco-tour-from-casablanca',
    '/tours/8-days-itinerary-tour-from-casablanca.html': '/tours/8-days-itinerary-tour-from-casablanca',
    '/tours/9-day-authentic-morocco-tour.html': '/tours/9-day-authentic-morocco-tour',
    '/tours/morocco-itinerary-9-days-desert-imperial-cities.html': '/tours/9-days-desert-imperial-cities',
    '/tours/10-days-morocco-couple-tour-packages.html': '/tours/10-days-morocco-couple-tour',
    '/tours/morocco-imperial-cities-tour-from-casablanca.html': '/tours/10-days-imperial-cities-tour',
    '/tours/12-days-morocco-tour-from-casablanca.html': '/tours/12-days-tour-from-casablanca',
    '/tours/12-days-morocco-tour.html': '/tours/12-days-morocco-tour',
    '/tours/private-12-days-trip-to-desert-marrakech.html': '/tours/private-12-days-desert-marrakech',
    '/tours/16-days-morocco-tour-from-casablanca.html': '/tours/16-days-morocco-tour-from-casablanca',
    '/tours/16-day-casablanca.html': '/tours/16-days-morocco-tour-from-casablanca',
    '/tours/3-days-desert-tour-from-marrakech-to-fes.html': '/tours/3-days-desert-tour-marrakech-to-fes',
    '/tours/4-days-marrakech-desert-tour.html': '/tours/4-days-marrakech-desert-tour',
    '/tours/5-days-tour-from-marrakech-to-merzouga.html': '/tours/5-days-tour-marrakech-to-merzouga',
    '/tours/11-days-morocco-classic-tour.html': '/tours/11-days-morocco-classic-tour',
    '/tours/itinerary-13-days-casablanca-tour.html': '/tours/13-days-casablanca-tour',
    '/tours/15-days-tour-from-casablanca.html': '/tours/15-days-tour-from-casablanca',
    '/tours/agafay-desert-sunset-camel-ride-dinner-under-the-stars.html': '/tours/agafay-desert-sunset-camel-ride',
    '/tours/one-day-trip-from-marrakech-to-essaouira-mogador.html': '/tours/day-trip-essaouira-mogador',
    '/tours/one-day-trip-from-marrakech-to-ouarzazate-and-the-ait-ben-haddou-.html': '/tours/day-trip-ait-ben-haddou',
    '/tours/one-day-trip-from-marrakech-to-the-ouzoud-waterfalls-and-berber-.html': '/tours/day-trip-ouzoud-waterfalls',
    '/tours/one-day-guided-tour-of-marrakech-city.html': '/tours/one-day-marrakech-city-tour',
    '/tours/ourika-valley-nature-wildlife-tour.html': '/tours/ourika-valley-nature-tour',
    '/tours/hot-air-balloon-in-marrakech.html': '/tours/hot-air-balloon-marrakech',
    '/tours/horse-riding-in-morocco.html': '/tours/horse-riding-morocco',
    '/tours/fantasia-chez-ali-marrakech.html': '/tours/fantasia-chez-ali-marrakech',
    '/tours/quad-biking-in-marrakech.html': '/tours/quad-biking-marrakech',
    '/tours/raid-buggy-in-marrakech.html': '/tours/raid-buggy-marrakech',
    '/tours/camel-riding.html': '/tours/camel-riding',

    // Non-.html legacy slugs
    '/tours/10-days-morocco-tour-from-casablanca': '/tours/10-days-imperial-cities-tour',
    '/tours/itinerary-6-days-tour-from-casablanca': '/tours/6-days-desert-tour-from-casablanca',
    '/tours/morocco-itinerary-9-days-desert-imperial-cities': '/tours/9-days-desert-imperial-cities',
    '/tours/10-days-morocco-couple-tour-packages': '/tours/10-days-morocco-couple-tour',
    '/tours/morocco-imperial-cities-tour-from-casablanca': '/tours/10-days-imperial-cities-tour',
    '/tours/12-days-morocco-tour-from-casablanca': '/tours/12-days-tour-from-casablanca',
    '/tours/private-12-days-trip-to-desert-marrakech': '/tours/private-12-days-desert-marrakech',
    '/tours/3-days-desert-tour-from-marrakech-to-fes': '/tours/3-days-desert-tour-marrakech-to-fes',
    '/tours/5-days-tour-from-marrakech-to-merzouga': '/tours/5-days-tour-marrakech-to-merzouga',
    '/tours/itinerary-13-days-casablanca-tour': '/tours/13-days-casablanca-tour',
    '/tours/agafay-desert-sunset-camel-ride-dinner-under-the-stars': '/tours/agafay-desert-sunset-camel-ride',
    '/tours/one-day-trip-from-marrakech-to-essaouira-mogador': '/tours/day-trip-essaouira-mogador',
    '/tours/one-day-trip-from-marrakech-to-ouarzazate-and-the-ait-ben-haddou-': '/tours/day-trip-ait-ben-haddou',
    '/tours/one-day-trip-from-marrakech-to-the-ouzoud-waterfalls-and-berber-': '/tours/day-trip-ouzoud-waterfalls',
    '/tours/one-day-guided-tour-of-marrakech-city': '/tours/one-day-marrakech-city-tour',
    '/tours/ourika-valley-nature-wildlife-tour': '/tours/ourika-valley-nature-tour',
    '/tours/hot-air-balloon-in-marrakech': '/tours/hot-air-balloon-marrakech',
    '/tours/horse-riding-in-morocco': '/tours/horse-riding-morocco',
    '/tours/quad-biking-in-marrakech': '/tours/quad-biking-marrakech',
    '/tours/raid-buggy-in-marrakech': '/tours/raid-buggy-marrakech',
  }
});
